joint1_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint1_joint
  pid: {p: 50, i: 0.1, d: 1.0}
joint2_position_controller:
  type: position_controllers/JointPositionController
  joint: arm_joint2_joint
  pid: {p: 50, i: 0.1, d: 1.0}
